### ISSUE TITLE
UI: Adding items within sections

### ISSUE THREAD

**Issue by justintadlock** [MachoThemes/epsilon-framework#70]
In Doctors and Testimonials sections, for example, the big blue button doesn't match the rest of the core WP UI.  I'd look at what core is doing with the Menus and Widgets sections.  You done this with the "Add a Section" button.  You should follow through within the individual page section repeating fields.

------

I'm attaching a couple of screenshots to help describe the other aspect of this.  If you could pull this off, it'd be awesome.  If not, what you have is good enough.

The first screenshot is showing how I'd like to see items (testimonials in this case) moved to main section.  That way, the user doesn't have to click the button to manage all testimonials.  Then, the "Add Testimonial" button can simply be to slide out the options for adding a testimonial.  And, clicking on an individual testimonial would allow you to manage that single testimonial in the slide out.

I hope that explains it well enough.  If not, the screenshots should help.  And, this is just an idea from a usability perspective.  Consider it low-priority.

![items-ui-001](https://user-images.githubusercontent.com/1816309/32409216-b4f706be-c175-11e7-943e-91e6b4427212.png)
![items-ui-002](https://user-images.githubusercontent.com/1816309/32409217-b6187a82-c175-11e7-8cb9-fe4338037d6a.png)

**Comment by cristianraiber** [comment]
@justintadlock - although we've met some technical limitations due to which we can't get what you've suggested in your screenshot above (that was our initial concept) ... I find it a bit easier to work with now, since you can keep multiple testimonials expanded at a time & copy-paste from one another easier. Basically, there's a bit more real estate room to work with. 

We are still considering ways to implement this, but having a field repeater inside a section repeater isn't possible at the moment.
